import axios from 'axios';

// Define the base URL for the backend Firebase database
const BACKEND_URL = 'https://expense-tracker-app-69828-default-rtdb.firebaseio.com';

// Store a new expense in the backend database
export async function storeExpense(expenseData) {
  // Send a POST request to store the expense data
  const response = await axios.post(BACKEND_URL + '/expenses.json', expenseData);
  // Extract and return the unique ID generated by Firebase
  const id = response.data.name;
  return id;
}

// Fetch all expenses from the backend database
export async function fetchExpenses() {
  // Send a GET request to retrieve all expenses
  const response = await axios.get(BACKEND_URL + '/expenses.json');

  const expenses = [];

  // Transform the response data into an array of expense objects
  for (const key in response.data) {
    const expenseObj = {
      id: key,
      amount: response.data[key].amount,
      date: new Date(response.data[key].date),
      description: response.data[key].description
    };
    expenses.push(expenseObj);
  }

  return expenses;
}

// Update an existing expense in the backend database
export function updateExpense(id, expenseData) {
  // Send a PUT request to update the expense with the given ID
  return axios.put(BACKEND_URL + `/expenses/${id}.json`, expenseData);
}

// Delete an existing expense from the backend database
export function deleteExpense(id) {
  // Send a DELETE request to remove the expense with the given ID
  return axios.delete(BACKEND_URL + `/expenses/${id}.json`);
}
